### PR TITLE
feat: add `preserveExtensions` option

### LINKED ISSUE #8: Enable use with non-transpiled TS
## Use case

We run our build using `sucrase` to transpile TS without type-checking (and rely on editors and ESLint to provide typing errors). This plugin is very useful as `sucrase` does not perform path substitution - however, it assumes every resolved path needs to have its extension replaced with `.js` - which is not the case, since those imports are then transpiled by `sucrase` anyway.

This causes `sucrase` to not find the imported modules, since the modules are still present in `.tsx?` form

## Proposal

Provide an option to disable extension substituion with `.js`.

### PR DESCRIPTION
**Pull request by Benjozork**
Fixes #8 

* [x] Add `preserveExtensions` option
* [x] Add tests
* [x] Edit documentation

### CODE REVIEW

**Review by aguther — APPROVED** [review]
LGTM

**Review by simonhaenisch — APPROVED** [review]
Thanks for the PR, looks good! Not breaking any existing behavior 👍

I'll just adjust the descriptions a bit because they were kind of negated.

**Comment by simonhaenisch** [comment]
Just released `1.3.0` 🚀

**Comment by Benjozork** [comment]
Thanks!

**Pull request merged**
